name = "nox-media"
compatibility_date = "2024-09-23" # This is crucial for Node.js built-in modules

[build]
command = "npm run build"

[site]
bucket = ".next/static"

[env.production]
# Production-specific settings can go here

[env.development]
# Development-specific settings can go here