name = "nox-media"
compatibility_date = "2024-09-23" # This is crucial for Node.js built-in modules
main = "worker.js" # Point to our worker script
node_compat = true # Enable Node.js compatibility

[build]
command = "npm run build && cp worker.js .next/standalone/"

# Specify where your static assets are located
[site]
bucket = ".next/static"

# Upload the Next.js standalone server directory
[[build.upload]]
format = "directory"
dir = ".next/standalone"
route = "/"

# Make sure Node.js built-ins are properly handled
[rules]
[rules.node_modules]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[miniflare]
kv_persist = true
cache_persist = true

[env.production]
workers_dev = true

[env.development]
workers_dev = true