name = "nox-media"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"] # Updated from node_compat to nodejs_compat

main = "worker.js"

[build]
command = "npm run build && cp worker.js .next/standalone/"

# Specify where your static assets are located
[site]
bucket = ".next/static"

# Worker routes
[[routes]]
pattern = "/*"
script = "worker.js"

# Worker environment variables
[vars]
NODE_ENV = "production"

[env.production]
workers_dev = true

[env.development]
workers_dev = true